blogtest/backweb/urls.py
"""__author__=wuliang"""
from django.conf.urls import url

from backweb import views

urlpatterns = [
	url(r'^login/', views.login, name='login'),
	url(r'^index/', views.index, name='index'),
	url(r'^article/', views.article, name='article'),
	url(r'^add_article/', views.add_article, name='add_article'),
	url(r'^add_category/', views.add_category, name= 'add_category'),
	url(r'^update_category/(\d+)', views.update_category, name='update_category'),
	url(r'^delete_category/', views.delete_category,name='delete_category'),

	url(r'^update_article/(\d+)', views.update_article, name='update_article'),
	url(r'^delete_article/', views.delete_article, name='delete_article'),
	url(r'^logout/', views.logout, name='logout'),
	url(r'^search/', views.search, name='search'),
	url(r'^alter_message/', views.alter_message, name='alter_message'),
]

blogtest/blogtest/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from blogtest.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls', namespace='web')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb'))
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

blogtest/web/urls.py
"""__author__=wuliang"""
from django.conf.urls import url

from web import views

urlpatterns = [
	url(r'^index/', views.index, name='index'),
	url(r'^info/(\d+)', views.info, name='info'),

]

blogtest/backweb/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class ArticleClass(models.Model):
	classname = models.CharField(max_length=20)
	alias = models.CharField(max_length=20,null=True,unique=True)
	count = models.IntegerField(default=0)
	description = models.CharField (max_length=150, null=True)
	fatherid = models.IntegerField(default=0)
	keyword = models.CharField(max_length=30,null=True)
	user = models.ForeignKey(User)

	class Meta:
		db_table = 'tb_articleclass'




class Article(models.Model):
	title = models.CharField(max_length=32)
	description = models.CharField(max_length=255)
	content = models.TextField()
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)
	status = models.BooleanField(default=True)
	keyword = models.CharField(max_length=20, null=True)
	count = models.IntegerField(default=0)
	img = models.ImageField(upload_to='article',null=True)
	articleclass = models.ForeignKey(ArticleClass)
	user = models.ForeignKey(User)

	class Meta:
		db_table = 'tb_article'

blogtest/backweb/forms.py
"""__author__=wuliang"""
from django import forms
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User


class UserLoginForm(forms.Form):
	username = forms.CharField(max_length=10, min_length=2, required=True,
							   error_messages={
								   'max_length': '用户名不能超过10位',
								   'min_length': '用户名不能短于4位',
								   'required': '用户名不能为空',
							   })
	password = forms.CharField(max_length=16,min_length=6,required=True,
							   error_messages={
								   'max_length': '密码不能超过16位',
								   'min_length': '密码不能小于6位',
								   'required': '密码不能为空',
							   })


class ArticleForm(forms.Form):
	title = forms.CharField(max_length=20, required=True, error_messages={
		'max_length': '标题不能长度不能超过20个字符',
		'required': '标题不能为空'
	})

	content = forms.CharField(required=True,
							  error_messages={
								  'required': '内容不能为空'
							  }
							  )
	keywords = forms.CharField(max_length=20, error_messages={
		'max_length': '关键字不能超过20个'
	})

	describe = forms.CharField(max_length=150, min_length=10, required=True,
							   error_messages={
								   'max_length': '描述不能超过150字符',
								   'min_length': '描述不能少于10个字符',
								   'required': '描述不能为空'
							   })
	category = forms.CharField()


	visibility = forms.CharField()

class ArticleClassForm(forms.Form):
	name = forms.CharField(max_length=20,min_length=2,required=True,
						error_messages={
							'max_length': '名称不能超过10字符',
							'min_length': '名称不能少于2个字符',
							'required': '名称不能为空'
						}
						   )
	alias = forms.CharField(max_length=20,min_length=2,required=True,
						error_messages={
							'max_length': '别名不能超过10字符',
							'min_length': '别名不能少于2个字符',
							'required': '别名不能为空'
						}
						   )
	fid = forms.IntegerField()
	keywords = forms.CharField(
		max_length=30, min_length=2, required=True,
		error_messages={
			'max_length': '关键字不能超过25字符',
			'min_length': '关键字不能少于2个字符',
			'required': '关键字不能为空'}
	)

	describe = forms.CharField(max_length=150, min_length=10, required=True,
							   error_messages={
								   'max_length': '描述不能超过150字符',
								   'min_length': '描述不能少于10个字符',
								   'required': '描述不能为空'
							   })


class MessageForm(forms.Form):
	username = forms.CharField (max_length=10, min_length=2, required=True,
								error_messages={
									'max_length': '用户名不能超过10位',
									'min_length': '用户名不能短于4位',
									'required': '用户名不能为空',
								})
	old_password = forms.CharField(max_length=16, min_length=6, required=True,
								error_messages={
									'max_length': '密码不能超过16位',
									'min_length': '密码不能小于6位',
									'required': '密码不能为空',
								})
	password = forms.CharField (max_length=16, min_length=6, required=True,
								error_messages={
									'max_length': '密码不能超过16位',
									'min_length': '密码不能小于6位',
									'required': '密码不能为空',
								})
	new_password = forms.CharField (max_length=16, min_length=6, required=True,
								error_messages={
									'max_length': '密码不能超过16位',
									'min_length': '密码不能小于6位',
									'required': '密码不能为空',
								})
	def clean(self):
		flag = check_password(self.cleaned_data.get('old_password'),
					   User.objects.filter (username=self.cleaned_data.get ('username')).first().password)
		if not flag:
			raise forms.ValidationError({'password': '密码错误'})
		if self.cleaned_data.get('password') != self.cleaned_data.get('new_password'):
			raise forms.ValidationError({'new_password': '确认密码与新密码不一致'})
		return self.cleaned_data

blogtest/backweb/views.py
import json

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.core.paginator import Paginator

from django.urls import reverse

from backweb.forms import UserLoginForm, ArticleForm, ArticleClassForm, MessageForm
from backweb.models import Article, ArticleClass


def login(request):
	if request.method == 'GET':
		return render(request, 'backweb/login.html')
	if request.method == 'POST':
		data = request.POST
		form = UserLoginForm(data)
		if not form.is_valid():
			return render(request, 'backweb/login.html', {'error': form.errors})
		user = auth.authenticate(username=form.cleaned_data.get('username'),
								 password=form.cleaned_data.get('password'))
		if not user:
			return render(request, 'backweb/login.html', {'msg': '密码错误'})
		auth.login(request,user)

		return HttpResponseRedirect(reverse('backweb:index'))


@login_required
def index(request):
	if request.method == 'GET':
		count = Article.objects.count()
		all_count = 0
		for art in Article.objects.filter(count__gt=0):
			all_count += art.count
		return render(request, 'backweb/index.html',{'count': count,
													 'all_count': all_count})

	if request.method == 'POST':
		pass

@login_required
def article(request):
	if request.method == 'GET':
		# 展示文章实现分页
		articles = Article.objects.filter(Q(status=0)|Q(status=1))
		paginator = Paginator(articles, 6)
		page = request.GET.get('page')
		if page:
			arts = paginator.page(page)
		else:
			page = 1
			arts = paginator.page(page)

		return render(request, 'backweb/article.html', {'arts': arts, 'page': page})




@login_required
def add_article(request):
	if request.method == 'GET':
		categorys = ArticleClass.objects.all()
		return render(request, 'backweb/add-article.html', {'categorys':categorys})

	if request.method == 'POST':
		form = ArticleForm(request.POST)
		articleclass = ArticleClass.objects.get(id=form.data.get('category'))
		if form.is_valid():
			Article.objects.create(

				title=form.cleaned_data.get('title'),
				description=form.cleaned_data.get('describe'),
				content=form.cleaned_data.get('content'),
				keyword=form.cleaned_data.get('keywords'),
				articleclass=articleclass,
				img=request.FILES.get('titlepic'),
				status=form.cleaned_data.get('visibility'),
				user=request.user,


			)
			articleclass.count += 1
			articleclass.save()

			return HttpResponseRedirect(reverse('backweb:article'))
		return render(request, 'backweb/add-article.html',{'error': form.errors})


@login_required
def add_category(request):
	if request.method == 'GET':
		categorys = ArticleClass.objects.all()
		return render(request, 'backweb/category.html',{'categorys': categorys})
	if request.method == 'POST':
		form = ArticleClassForm(request.POST)
		categorys = ArticleClass.objects.all()
		if form.is_valid():

			ArticleClass.objects.create(
				classname=form.cleaned_data.get('name'),
				alias=form.cleaned_data.get('alias'),
				keyword=form.cleaned_data.get('keywords'),
				description=form.cleaned_data.get('describe'),
				fatherid=form.cleaned_data.get('fid'),
				user=request.user
			)
			return HttpResponseRedirect(reverse('backweb:add_category'))
		else:
			return render(request, 'backweb/category.html', {'error':form.errors,'categorys':categorys})

@login_required
def update_category(request,id):
	if request.method == 'GET':
		categorys = ArticleClass.objects.all()
		category = ArticleClass.objects.get(pk=id)
		return render(request, 'backweb/update-category.html', {'category':category,'categorys':categorys})

	if request.method == 'POST':
		form = ArticleClassForm(request.POST)
		categorys = ArticleClass.objects.all()
		category = ArticleClass.objects.get(pk=id)
		if form.is_valid():
			category.classname = form.cleaned_data.get('name')
			category.user = request.user
			category.alias = form.cleaned_data.get('alias')
			category.keyword = form.cleaned_data.get('keywords')
			category.description = form.cleaned_data.get('describe')
			category.fatherid = form.cleaned_data.get ('fid')

			category.save()

			return HttpResponseRedirect(reverse('backweb:add_category'))

		else:
			return render(request, 'backweb/update-category.html', {'error':form.errors,
																	'category':category,
																	'categorys':categorys})

@login_required
def delete_category(request):
	if request.method == 'POST':
		id = request.POST.get('id')
		articleclass = ArticleClass.objects.get(pk=id)
		articleclass.article_set.all().delete()
		articleclass.delete()

		categorys = ArticleClass.objects.all()

		return HttpResponse('成功')


def update_article(request, id):
	if request.method == 'GET':
		art = Article.objects.get(pk=id)
		categorys = ArticleClass.objects.all()

		return render(request, 'backweb/update-article.html', {'art':art, 'categorys':categorys})

	if request.method == 'POST':
		form = ArticleForm(request.POST)
		if form.is_valid():

			article = Article.objects.get(pk=id)
			# 减掉原来栏目的文章数量一个
			article.articleclass.count -= 1
			article.save ()

			article.articleclass = ArticleClass.objects.get(id=form.cleaned_data.get('category'))
			# 增加新栏目的文章数量一个
			article.articleclass.count += 1


			article.user = request.user
			article.keyword = form.cleaned_data.get('keywords')
			article.title = form.cleaned_data.get ('title')
			article.description = form.cleaned_data.get ('describe')
			article.content = form.cleaned_data.get ('content')
			article.img = request.FILES.get ('titlepic')
			article.status = form.cleaned_data.get ('visibility')
			article.save()

			return HttpResponseRedirect(reverse('backweb:article'))


def delete_article(request):
	if request.method == 'GET':
		return HttpResponseRedirect(reverse('backweb:article'))
	if request.method == 'POST':
		article = Article.objects.get(pk=request.POST.get('id'))
		if article.articleclass.count>0:
			article.articleclass.count -= 1
		article.status = 2
		article.save()

		return HttpResponse('删除成功')

@login_required
def logout(request):
	if request.method == 'GET':
		auth.logout(request)
		return HttpResponseRedirect(reverse('backweb:login'))

def search(request):
	if request.method == 'POST':
		# 展示文章实现分页
		keys = request.POST.get('keys')
		articles = Article.objects.filter (Q (status=0) | Q (status=1))\
			.filter(Q(title__contains=keys)|
					Q(keyword__contains=keys)|
					Q(description__contains=keys))

		paginator = Paginator (articles, 6)
		page = request.POST.get ('n_page')
		if page:
			arts = paginator.page (page)
		else:
			page = 1
			arts = paginator.page (page)

		return render (request, 'backweb/article.html', {'arts': arts, 'page': page})


@login_required
def alter_message(request):
	if request.method == 'GET':
		return render(request, 'backweb/change_message.html')
	if request.method == 'POST':
		form = MessageForm(request.POST)

		if form.is_valid():
			user = User.objects.get(pk=request.user.id)
			user.clean()

			user.username = form.cleaned_data.get('username')
			user.password = make_password(form.cleaned_data.get('password'))
			user.save()
			return HttpResponseRedirect(reverse('backweb:login'))
		return render(request,'backweb/change_message.html',{'error':form.errors})

blogtest/templates/backweb/category.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>栏目 - 异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/backweb/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/backweb/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/backweb/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/backweb/images/icon/icon.png">
<link rel="shortcut icon" href="/static/backweb/images/icon/favicon.ico">
<script src="/static/backweb/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/static/backweb/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
<section class="container-fluid">
  <header>
        <nav class="navbar navbar-default navbar-fixed-top">
        {% block container-fluid %}
         <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">

            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a href='{% url 'backweb:alter_message' %}' title="查看或修改个人信息" >个人信息</a></li>

              </ul>
            </li>
            <li><a href="{% url 'backweb:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>

          </ul>
          <form action="{% url 'backweb:search' %}" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input name="keys" type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
                <input type="hidden" value="{{ page }}" name="n_page">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
        {% endblock %}
    </nav>
  </header>
  <div class="row">
 <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'backweb:article' %}">文章</a></li>

      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'backweb:add_category' %}">栏目</a></li>

          <ul class="dropdown-menu" aria-labelledby="otherMenu">


          </ul>
        </li>
      </ul>

    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <div class="row">
        <div class="col-md-5">
          <h1 class="page-header">添加</h1>
          <form action="{% url 'backweb:add_category' %}" method="post" autocomplete="off">
            <div class="form-group">
              <label for="category-name">栏目名称</label>
              <input type="text" id="category-name" name="name" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
              <span class="prompt-text">这将是它在站点上显示的名字。</span>
                {{ error.name }}
            </div>
            <div class="form-group">
              <label for="category-alias">栏目别名</label>
              <input type="text" id="category-alias" name="alias" class="form-control" placeholder="在此处输入栏目别名" required autocomplete="off">
              <span class="prompt-text">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。

              </span>
                {{ error.alias }}
            </div>
            <div class="form-group">
              <label for="category-fname">父节点</label>
              <select id="category-fname" class="form-control" name="fid">
                <option value="0" selected>无</option>
                  {%  for cate in categorys %}
                <option value="{{ cate.id }}">{{ cate.classname }}</option>
                  {% endfor %}

              </select>
              <span class="prompt-text">栏目是有层级关系的，您可以有一个“音乐”分类目录，在这个目录下可以有叫做“流行”和“古典”的子目录。</span>
                {{ error.fid }}
            </div>
            <div class="form-group">
              <label for="category-keywords">关键字</label>
              <input type="text" id="category-keywords" name="keywords" class="form-control" placeholder="在此处输入栏目关键字" autocomplete="off">
              <span class="prompt-text">关键字会出现在网页的keywords属性中。</span>
                {{ error.keywords }}
            </div>
            <div class="form-group">
              <label for="category-describe">描述</label>
              <textarea class="form-control" id="category-describe" name="describe" rows="4" autocomplete="off"></textarea>
              <span class="prompt-text">描述会出现在网页的description属性中。</span>
                {{ error.describ }}
            </div>
            <button class="btn btn-primary" type="submit" name="submit">添加新栏目</button>
          </form>
        </div>
        <div class="col-md-7">
          <h1 class="page-header">管理 <span class="badge">3</span></h1>
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th><span class="glyphicon glyphicon-paperclip"></span> <span class="visible-lg">ID</span></th>
                  <th><span class="glyphicon glyphicon-file"></span> <span class="visible-lg">名称</span></th>
                  <th><span class="glyphicon glyphicon-list-alt"></span> <span class="visible-lg">别名</span></th>
                  <th><span class="glyphicon glyphicon-pushpin"></span> <span class="visible-lg">总数</span></th>
                  <th><span class="glyphicon glyphicon-pencil"></span> <span class="visible-lg">操作</span></th>
                </tr>
              </thead>
              <tbody>
              {% for cate in categorys %}
                <tr>
                  <td>{{ cate.id }}</td>
                  <td>{{ cate.classname }}</td>
                  <td>{{ cate.alias }}</td>
                  <td>{{ cate.count }}</td>
                  <td><a href="{% url 'backweb:update_category' cate.id %}">修改</a> <a  class="delete_class" rel="{{ cate.id }}">删除</a></td>
                </tr>
              {% endfor %}

              </tbody>
            </table>
            <span class="prompt-text"><strong>注：</strong>删除一个栏目也会删除栏目下的文章和子栏目,请谨慎删除!</span> </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script src="/static/backweb/js/bootstrap.min.js"></script>
<script src="/static/backweb/js/admin-scripts.js"></script>
<script>
//是否确认删除
$(function(){   
	$(".delete_class").click(function(){
		var name = $(this);
		var id = name.attr("rel"); //对应id

		{#if (window.event.srcElement.outerText === "删除")#}
		{#{#}
        if(window.confirm("此操作不可逆，是否确认？"))
        {
            $.ajax({
                type: "POST",
                url: "{% url 'backweb:delete_category' %}",
                data: {'id':id},
                dataType: 'json',
                cache: false, //不缓存此页面
                success: function (data) {
                    window.location.replace(location.href);
                },
                error: function(data){
                  window.location.reload()
                }
            });
			};

	});
});
</script>
</body>
</html>

blogtest/templates/backweb/update-category.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>修改栏目 - 异清轩博客管理系统</title>
<link rel="stylesheet" type="text/css" href="/static/backweb/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/backweb/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/backweb/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="/static/backweb/images/icon/icon.png">
<link rel="shortcut icon" href="/static/backweb/images/icon/favicon.ico">
<script src="/static/backweb/js/jquery-2.1.4.min.js"></script>
<!--[if gte IE 9]>
  <script src="/static/backweb/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/respond.min.js" type="text/javascript"></script>
  <script src="/static/backweb/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>

<body class="user-select">
<section class="container-fluid">
  <header>
        <nav class="navbar navbar-default navbar-fixed-top">
        {% block container-fluid %}
        <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">切换导航</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          <a class="navbar-brand" href="/">YlsatCMS</a> </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">

            <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
              <ul class="dropdown-menu dropdown-menu-left">
                <li><a href='{% url 'backweb:alter_message' %}' title="查看或修改个人信息" >个人信息</a></li>

              </ul>
            </li>
            <li><a href="{% url 'backweb:logout' %}" onClick="if(!confirm('是否确认退出？'))return false;">退出登录</a></li>
          </ul>
          <form action="{% url 'backweb:search' %}" method="post" class="navbar-form navbar-right" role="search">
            <div class="input-group">
              <input name="keys" type="text" class="form-control" autocomplete="off" placeholder="键入关键字搜索" maxlength="15">
                <input type="hidden" value="{{ page }}" name="n_page">
              <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
              </span> </div>
          </form>
        </div>
      </div>
        {% endblock %}
    </nav>
  </header>
  <div class="row">
    <aside class="col-sm-3 col-md-2 col-lg-2 sidebar">

      <ul class="nav nav-sidebar">
        <li><a href="{% url 'backweb:article' %}">文章</a></li>


      </ul>
      <ul class="nav nav-sidebar">
        <li><a href="{% url 'backweb:add_category' %}">栏目</a></li>

          <ul class="dropdown-menu" aria-labelledby="otherMenu">


          </ul>
        </li>
      </ul>

    </aside>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-lg-10 col-md-offset-2 main" id="main">
      <h1 class="page-header">修改栏目</h1>
      <form action="{% url 'backweb:update_category' category.id %}" method="post">
        <div class="form-group">
          <label for="category-name">栏目名称</label>
          <input type="text" id="category-name" name="name" value="{{ category.classname }}" class="form-control" placeholder="在此处输入栏目名称" required autocomplete="off">
          <span class="prompt-text">这将是它在站点上显示的名字。</span> </div>
        <div class="form-group">
          <label for="category-alias">栏目别名</label>
          <input type="text" id="category-alias" name="alias" value="{{ category.alias }}" class="form-control" placeholder="在此处输入栏目别名" required autocomplete="off">
          <span class="prompt-text">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span> </div>
        <div class="form-group">
          <label for="category-fname">父节点</label>
          <select id="category-fname" class="form-control" name="fid">
            <option value="0" selected>无</option>
              {% for cate in categorys %}
            <option value="{{ cate.id }}">{{ cate.classname }}</option>
              {% endfor %}
          </select>
          <span class="prompt-text">栏目是有层级关系的，您可以有一个“音乐”分类目录，在这个目录下可以有叫做“流行”和“古典”的子目录。</span> </div>
        <div class="form-group">
          <label for="category-keywords">关键字</label>
          <input type="text" id="category-keywords" name="keywords" value="{{ category.keyword }}" class="form-control" placeholder="在此处输入栏目关键字" autocomplete="off">
          <span class="prompt-text">关键字会出现在网页的keywords属性中。</span> </div>
        <div class="form-group">
          <label for="category-describe">描述</label>
          <textarea class="form-control" id="category-describe" name="describe" rows="4" autocomplete="off">{{ category.description }}</textarea>
          <span class="prompt-text">描述会出现在网页的description属性中。</span> </div>
        <button class="btn btn-primary" type="submit" name="submit">更新</button>
      </form>
    </div>
  </div>
</section>

<script src="/static/backweb/js/bootstrap.min.js"></script>
<script src="/static/backweb/js/admin-scripts.js"></script>
</body>
</html>