blogtest/blogtest/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from blogtest.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include('web.urls', namespace='web')),
    url(r'^backweb/', include('backweb.urls', namespace='backweb'))
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

blogtest/web/urls.py
"""__author__=wuliang"""
from django.conf.urls import url

from web import views

urlpatterns = [
	url(r'^index/', views.index, name='index'),
	url(r'^info/(\d+)', views.info, name='info'),

]

blogtest/templates/web/base.html
<!doctype html>
<html>
<head>


{% block meta %}
<meta charset="utf-8">
<title>我的个人博客</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}


{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'web/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/m.css' %}">
{% endblock %}


{% block js %}
    {% load static %}
    <script src="{% static 'web/js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'web/js/comm.js' %}" type="text/javascript"></script>
    <!--[if lt IE 9]>
        <script src="{% static 'js/modernizr.js' %}"></script>
    <![endif]-->
{% endblock %}




</head>
<body>


{% block header %}
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{% url 'web:index' %}">网站首页</a></li>
{#      <li><a href="{% url 'web:share' %}">我的相册</a></li>#}
{#      <li><a href="{% url 'web:list' %}">我的日记</a></li>#}
{#      <li><a href="{% url 'web:about' %}">关于我</a></li>#}
{#      <li><a href="{% url 'web:gbook' %}">留言</a></li>#}
{#      <li><a href="{% url 'web:info' %}">内容页</a></li>#}
{#      <li><a href="{% url 'web:infopic' %}">内容页</a></li>#}
    </ul>
</nav>
</header>
{% endblock %}

<article>
  <aside class="l_box">

      {% block about_me %}
{#      <div class="about_me">#}
{#        <h2>关于我</h2>#}
{#        <ul>#}
{#          <i>#}
{#              {% load static %}#}
{#              <img src="{% static 'web/images/4.jpg' %}">#}
{#          </i>#}
{#          <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>#}
{#        </ul>#}
{#      </div>#}
      {% endblock %}

      {% block wdxc %}
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>

            {% for art in arts %}
                {% if forloop.counter <= 6 %}
            <li>
              <a href="#">

              <img src="/media/{{ art.img }}">
                  {% endif %}
          </a></li>
            {% endfor %}

        </ul>
      </div>
      {% endblock %}

      {% block search %}
      <div class="search">
        <form action="{% url 'web:index' %}" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      {% endblock %}


      {% block feilei %}
      <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for cate in categorys %}
          <li><a href="{% url 'web:index' %}?cate_id={{ cate.id }}">{{ cate.classname }}（{{ cate.count }}）</a></li>
            {% endfor %}
        </ul>
      </div>
      {% endblock %}


      {% block content %}
{#      <div class="tuijian">#}
{#        <h2>站长推荐</h2>#}
{#        <ul>#}
{#            {% for art in arts %}#}
{#          <li><a href="/">{{ art.title }}</a></li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#      </div>#}
    {% endblock %}

    {% block content2 %}

    {% endblock %}



    {% block guanzhu %}

    {% endblock %}

  </aside>

 {% block custom %}
  <main class="r_box">




    {% for art in arts %}
    <li><i><a href="/">

        <img src="/media/{{ art.img }}">
    </a></i>
      <h3><a href="{% url 'web:info' art.id %}">{{ art.title }}</a></h3>
      <p>{{ art.description|safe }}</p>
    </li>
  {% endfor %}


  </main>
{% endblock %}
</article>
<footer>
  <p>Design by <a href="#" target="_blank">个人博客</a> <a href="/">蜀ICP备110023xx号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

blogtest/templates/web/index.html
{% extends 'web/base.html' %}

blogtest/templates/web/info.html
{%  extends 'web/base.html' %}

{% block css %}
    {{  block.super  }}
    {% load static %}
    <link href="{% static 'web/css/info.css' %}" rel="stylesheet">

{% endblock %}










{% block custom %}

  <main>
    <div class="infosbox">
      <div class="newsview">
        <h3 class="news_title" id="title"></h3>
        <div class="bloginfo">
          <ul>
            <li class="author">作者：<a href="#" id="author">{{ art.user.username }}</a></li>

            <li class="lmname">分类：<a href="#">{{ art.articleclass.classname }}</a></li>
                 <li class="lmname"><a href="#" id="cname"></a></li>
              <li class="timer">创建时间：<a href="#">{{ art.create_time }}</a></li>
               <li class="timer" id="creat_time"></li>
              <li class="view">阅读数：<a href="#">{{ art.count }}</a></li>
          </ul>
        </div>
        <div class="tags">
             <h2>{{ art.title }}</h2>
            <a href="#" target="_blank">{{ art.keyword }}</a> &nbsp;

        </div>
          <div id="con">
              {{ art.content|safe }}
          </div>

      </div>

      <div class="nextinfo">
          {% if preart != None %}
        <p>上一篇：<a href="{% url 'web:info' preart.id %}">{{ preart.title }}</a></p>
          {% endif %}

        {% if nextart != None %}
        <p>下一篇：<a href="{% url 'web:info' nextart.id %}">{{ nextart.title }}</a></p>
        {% endif %}
      </div>

    </div>
  </main>
{% endblock %}